version: '3.4'

services:
  api:
    build: 
      context: .
      target: development
    volumes:
      - db-data:/user/src/app
      - /user/src/app/node_modules
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:10.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/user/src/postgresql/data      
volumes:
  db-data:
       